<!DOCTYPE html>
<html>
<head>
    <title>Sales Transformer</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>

<table class="table table-striped">
  <tr>
      <th>Transformations</th>
  </tr>



    <?php
        foreach($this->paginator as $sale)
        {
            echo '
        <tr>
            <td>'.$sale.'</td>
        </tr>';
        }


    echo $this->paginator;
    ?>
</table>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'controls.phtml'); ?>
</body>
</html>